version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: netflix_db_postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: always

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    env_file:
      - .env
    volumes:
      - ./dataset:/app/dataset
      - ./app:/app
    depends_on:
      postgres:
        condition: service_healthy

  db_init:
    image: postgres:14-alpine
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      app:
        condition: service_completed_successfully
    volumes:
      - ./Scripts_SQL:/scripts
    environment:
      - PGPASSWORD=${POSTGRES_PASSWORD}
    entrypoint: >
      sh -c "
        psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /scripts/1_schema.sql &&
        psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /scripts/2_inserts.sql &&
        psql -h postgres -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /scripts/3__cleanup.sql
      "